# Numberblocks Series Configuration
# Educational CBeebies cartoon - learn to count with Numberblocks

series_name: "Numberblocks"
description: "Learn to count with the Numberblocks - educational CBeebies cartoon"

naming_pattern: "S{season:02d}E{episode:02d}_{title}.mp4"
directory_pattern: "Season_{season}_HD"

quality: 1080

subtitles:
  enabled: true
  lang: "en"
  embed: true

# Episodes with video IDs (all 129 episodes found via Tavily search)
episodes:
  Season 1:
    - title: "S01E01 One"
      id: "jVeYnCehEFE"
    - title: "S01E02 Another One"
      id: "bz2oWyDjgbc"
    - title: "S01E03 Two"
      id: "aJzaNIpbUZo"
    - title: "S01E04 Three"
      id: "6-duQqX5ECs"
    - title: "S01E05 One Two Three"
      id: "IqkSbJqplpg"
    - title: "S01E06 Four"
      id: "Wafr8h4EsXg"
    - title: "S01E07 Five"
      id: "-U1wQ0gu0Es"
    - title: "S01E08 Three Little Pigs"
      id: "yKAttOvgWJc"
    - title: "S01E09 Off We Go"
      id: "37E3wokWzlU"
    - title: "S01E10 How to Count"
      id: "Ap5kgJ-bpEQ"
    - title: "S01E11 Stampolines"
      id: "M2u_jRHYUh0"
    - title: "S01E12 The Whole of Me"
      id: "fJ6k7vkV99o"
    - title: "S01E13 The Terrible Twos"
      id: "Vyx-oZpnPhY"
    - title: "S01E14 Holes"
      id: "Kv_j6gpD5Jo"
    - title: "S01E15 Hide and Seek"
      id: "q4RTnmfOSNI"

  Season 2:
    - title: "S02E01 Six"
      id: "X5Q18PkuLtM"
    - title: "S02E02 Seven"
      id: "NVJ7uXC1tYU"
    - title: "S02E03 Eight"
      id: "4DBmy4sOFis"
    - title: "S02E04 Nine"
      id: "5hGh6rqH4U4"
    - title: "S02E05 Ten"
      id: "ZNNUo-uQYwQ"
    - title: "S02E06 Just Add One"
      id: "S7CYJ9US2fk"
    - title: "S02E07 Blast Off"
      id: "O7VKyV43SBE"
    - title: "S02E08 Counting Sheep"
      id: "BO_pxx340iU"
    - title: "S02E09 Double Trouble"
      id: "CD4oKyOuINc"
    - title: "S02E10 The Three Threes"
      id: "QR1_9b4H_Y0"
    - title: "S02E11 Odds and Evens"
      id: "UdmHrpyZfQc"
    - title: "S02E12 Fluffies"
      id: "3pbyveE9C-4"
    - title: "S02E13 The Two Tree"
      id: "SkuHXMiJwFw"
    - title: "S02E14 Numberblock Castle"
      id: "cxGC0G273KI"
    - title: "S02E15 Ten Green Bottles"
      id: "ynTb9shdZLY"

  Season 3:
    - title: "S03E01 Once Upon a Time"
      id: "xnHUf9zqU_U"
    - title: "S03E02 Blockzilla"
      id: "Ii3E4zLEAuU"
    - title: "S03E03 The Numberblocks Express"
      id: "9UxTopiIUvM"
    - title: "S03E04 Fruit Salad"
      id: "NtQplzWz-uQ"
    - title: "S03E05 Zero"
      id: "LtmpIjNnqsI"
    - title: "S03E06 Now We Are Six to Ten"
      id: "uAuf7o4AkeA"
    - title: "S03E07 Numberblobs"
      id: "fng05gvXr9c"
    - title: "S03E08 Building Blocks"
      id: "iFvpDuT6d9I"
    - title: "S03E09 Peekaboo"
      id: "AAvZQsppeLE"
    - title: "S03E10 Hiccups"
      id: "yk4NteouHdI"
    - title: "S03E11 Whats the Difference"
      id: "s62mQ0oh9Lc"
    - title: "S03E12 Numberblock Rally"
      id: "rB9Xs0DR864"
    - title: "S03E13 Five and Friends"
      id: "gUnU4hUqeR0"
    - title: "S03E14 Octoblock to the Rescue"
      id: "FRGaDEmb4tI"
    - title: "S03E15 Ten Again"
      id: "xd4KfYY_fCs"
    - title: "S03E16 Flatland"
      id: "YA9sJ1RIdu0"
    - title: "S03E17 Pattern Palace"
      id: "Ev0TbEfkMCU"
    - title: "S03E18 The Legend of Big Tum"
      id: "07TDOl3Won8"
    - title: "S03E19 Mirror Mirror"
      id: "D-w6zSAAlkk"
    - title: "S03E20 The Wrong Number"
      id: "V13dlKqRL1E"
    - title: "S03E21 Eleven"
      id: "TozH7t_cymc"
    - title: "S03E22 Twelve"
      id: "TnCmfAdbWv8"
    - title: "S03E23 The Way of the Rectangle"
      id: "PcCXuqmvfWM"
    - title: "S03E24 Ride the Rays"
      id: "XnMPuxDtrbE"
    - title: "S03E25 Block Star"
      id: "myDRecuhRgk"
    - title: "S03E26 Thirteen"
      id: "oaKd5Q9HLIQ"
    - title: "S03E27 Fourteen"
      id: "2lrGQZlhWQ8"
    - title: "S03E28 Fifteen"
      id: "mkm2CYsmKLA"
    - title: "S03E29 Tween Scenes"
      id: "D-s8jUTJEQM"
    - title: "S03E30 Steps Squads"
      id: "Y4Fx3z5fAWY"

  Season 5:
    - title: "S05E01 Your Turn"
      id: "hnMkf3ZtFfU"
    - title: "S05E02 Now You See Us"
      id: "OWgRsFw0iU0"
    - title: "S05E03 Tens Top Ten"
      id: "gVdjzgkBrXg"
    - title: "S05E04 Whats My Number"
      id: "rM7u9b_nPX0"
    - title: "S05E05 Fun Times One Times Table"
      id: "0wrG2g2RnLQ"
    - title: "S05E06 The Many Friends of Twenty"
      id: "V9ZNvN7PedY"
    - title: "S05E07 Ten Vaulting"
      id: "ZORpBQ5CSTo"
    - title: "S05E08 Twoland"
      id: "AXU_r2WM59Q"
    - title: "S05E09 Two Times Shoe Shop"
      id: "MYVeEh4ncuE"
    - title: "S05E10 Odd Side Story"
      id: "Bcu8k_8LTxY"
    - title: "S05E11 How Rectangly"
      id: "WYDFwDlopOY"
    - title: "S05E12 Rectangle Racers"
      id: "NjlYk5262IA"
    - title: "S05E13 The Team Factor"
      id: "b8qe06QXi1Q"
    - title: "S05E14 Hidden Talents"
      id: "3XsXG6ynq00"
    - title: "S05E15 Making Patterns"
      id: "r7emwN5bszA"
    - title: "S05E16 Now In 3D"
      id: "lfAd7eFFbsI"
    - title: "S05E17 Club Picnic"
      id: "-KFdq63cVVo"
    - title: "S05E18 Circus of Threes"
      id: "O7ksWrvSn5k"
    - title: "S05E19 Too Many Threes"
      id: "YMkghWylWkY"
    - title: "S05E20 Figure It Out"
      id: "CqNt4_hnLmg"
    - title: "S05E21 Snow Day Doubles"
      id: "BdS2nD95PbM"
    - title: "S05E22 Steps Versus Squares"
      id: "Z-0G5xP_aR4"
    - title: "S05E23 Puzzle Square"
      id: "pgDEUlQ4J2Q"
    - title: "S05E24 Four On The Floor"
      id: "L8pXlMXbLBo"
    - title: "S05E25 Sky High Fives"
      id: "jEC-xeM4gio"
    - title: "S05E26 One Giant Step Squad"
      id: "ZoSlJaVaeDI"
    - title: "S05E27 Square on the Moon"
      id: "DFXx5nVIz_w"
    - title: "S05E28 Heroes with Zeroes"
      id: "mtcTEOWcPTA"
    - title: "S05E29 What If"
      id: "jrw0JCYLC_Q"
    - title: "S05E30 100 Ways to Leave the Planet"
      id: "qZwzZiX8K4s"

  Season 7:
    - title: "S07E01 Grid Unlocked"
      id: "5ghkoxROcso"
    - title: "S07E02 Friendly Fours Beach Day"
      id: "CV_JB1_rq-4"
    - title: "S07E03 All-star Line-up"
      id: "z7YqQW1vDms"
    - title: "S07E04 Rescue Racers"
      id: "jxpcw90-2_E"
    - title: "S07E05 The Rolling Sixes"
      id: "DDYPb77d054"
    - title: "S07E06 Remix the Sixes"
      id: "MT_byjHRC78"
    - title: "S07E07 Grid Games Galore"
      id: "cG3yPK6adlY"
    - title: "S07E08 The Rainbow Makers"
      id: "rinSXmlgESM"
    - title: "S07E09 Sail the Seven Seas"
      id: "mkyI5Aww1GQ"
    - title: "S07E10 We Need Another Hero"
      id: "mU_EDUgkCZ4"
    - title: "S07E11 Super Eights Assemble"
      id: "kC5C1mx7pto"
    - title: "S07E12 Seventy-twos Super Surprise"
      id: "UddOiJkh_Ao"
    - title: "S07E13 The Magical Nines"
      id: "H0paRYi-Ek4"
    - title: "S07E14 Nines Time to Shine"
      id: "qbjaIN2xrx4"
    - title: "S07E15 Space Division"
      id: "S5zjj8FWW04"

  Season 8:
    - title: "S08E01 The Third Button"
      id: "VrTfmsIq_Rk"
    - title: "S08E02 The Great Bug Race"
      id: "atGvlUlnvcU"
    - title: "S08E03 The Big Picture"
      id: "fTZt5yHk630"
    - title: "S08E04 Space Repair"
      id: "sgEUnHCuIZ4"
    - title: "S08E05 Capacity for Magic"
      id: "E_zTmPPEzQk"
    - title: "S08E06 How Many Smoothies"
      id: "HGM2aJANpu0"
    - title: "S08E07 Odd Block Club"
      id: "X0N8cRagHPk"
    - title: "S08E08 Five Makes a Wish"
      id: "O9mifcDmWJE"
    - title: "S08E09 Number Rescue Go"
      id: "I_TUzEK3ZOU"
    - title: "S08E10 The Best House Band in Numberland"
      id: "LuHamTVKMFM"
    - title: "S08E11 Double Duets"
      id: "F4LK3CEV-_0"
    - title: "S08E12 Double Doors Double Locked"
      id: "M3Ig3c0PGFc"
    - title: "S08E13 The All Knowing Nine"
      id: "csi2iPXqphE"
    - title: "S08E14 Subtraction Somersaults"
      id: "LFY7CK0V8ak"
    - title: "S08E15 Tenpin Tournament"
      id: "ZY5_H8iuNog"

  Specials:
    - title: "S00E01 Treasure Of Hexagon Island"
      id: "SVWo8e0Eks"
    - title: "S00E02 Twelve Days Of Christmas"
      id: "5j8zQFn9hgE"
    - title: "S00E03 About Time"
      id: "oyaDS_C3mOQ"
    - title: "S00E04 Double Back"
      id: "tpeUFIzG_Zg"
    - title: "S00E05 Escape to Space"
      id: "nWsJsQ0RUUg"
